name: clean_chat_app
description: "清晰架构的聊天应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 状态管理
  provider: ^6.1.2
  
  # 网络请求
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  
  # 本地存储
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # 路由管理
  go_router: ^14.6.2
  
  # UI组件
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  
  # 工具类
  equatable: ^2.0.5
  intl: ^0.19.0
  logger: ^2.4.0
  dartz: ^0.10.1
  
  # 依赖注入
  get_it: ^8.0.2
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # 代码生成
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.4
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: PingFang
      fonts:
        - asset: assets/fonts/PingFang-Regular.ttf
        - asset: assets/fonts/PingFang-Medium.ttf
          weight: 500
        - asset: assets/fonts/PingFang-Bold.ttf
          weight: 700